<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="contactform.php" method="post">
<input type="text" name="name" placeholder="FULL NAME">
<input type="mail" name="mail" placeholder="Email">
<input type="text" name="subject" placeholder="Subject">
<textarea name="message" placeholder="message" cols="30" rows="10"></textarea>
<button type="submit" name="submit" >SEND MAIL</button>
</form>
    
</body>
</html>